# Generated by Django 3.1.2 on 2022-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220123_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='school.Teacher'),
        ),
    ]
